import {
  Check,
  Column,
  Entity,
  OneToMany,
  PrimaryGeneratedColumn,
  Unique,
} from 'typeorm';
import { Order } from './order.entity';
import { Product } from './product.entity';

/**
 * users — і покупці, і продавці: у маркетплейсі одна людина може бути обома,
 * тож окремих таблиць немає, а роль визначає наявність звʼязків.
 *
 * Ключ — bigint GENERATED BY DEFAULT AS IDENTITY, а не serial: serial це
 * sequence з default збоку, з окремими правами й болем при ALTER.
 * BY DEFAULT (а не ALWAYS) — свідомо: детермінований seed вставляє явні id,
 * і саме це робить його ідемпотентним.
 *
 * TypeORM віддає bigint РЯДКОМ, а не числом — 2^53 не вміщає bigint, тож
 * драйвер не ризикує точністю. Тип поля тут `string` не помилка.
 */
@Entity({ name: 'users' })
@Unique('users_email_unique', ['email'])
@Check('users_email_shape', `position('@' IN email) > 1`)
@Check('users_full_name_filled', 'length(btrim(full_name)) > 0')
@Check('users_city_filled', 'length(btrim(city)) > 0')
export class User {
  @PrimaryGeneratedColumn('identity', {
    type: 'bigint',
    generatedIdentity: 'BY DEFAULT',
  })
  id!: string;

  @Column({ type: 'text' })
  email!: string;

  @Column({ type: 'text', name: 'full_name' })
  fullName!: string;

  @Column({ type: 'text' })
  city!: string;

  @Column({ type: 'boolean', name: 'is_active', default: true })
  isActive!: boolean;

  // Звичайна колонка з DEFAULT now(), а не @CreateDateColumn: той завжди
  // перезаписує значення поточним часом, а детермінованому seed потрібні
  // фіксовані дати (у orders від них ще й залежить CHECK на paid_at).
  @Column({ type: 'timestamptz', name: 'created_at', default: () => 'now()' })
  createdAt!: Date;

  /**
   * Товари, які користувач продає. onDelete у зворотному боці (Product.seller):
   * RESTRICT — видалити продавця, доки в каталозі є його товари, не можна.
   */
  @OneToMany(() => Product, (product) => product.seller)
  products!: Product[];

  /** Замовлення, які користувач зробив як покупець. Теж RESTRICT. */
  @OneToMany(() => Order, (order) => order.buyer)
  orders!: Order[];
}
