import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * ДЗ-14: те, чого бракувало для конкурентних операцій.
 *
 *   users.balance_cents — гаманець покупця; списується в тій самій транзакції,
 *                         що й декремент stock (src/checkout.ts);
 *   tasks              — outbox-черга post-processing; задача створюється в тій
 *                         самій транзакції, що й замовлення, а розбирають її
 *                         воркери через FOR UPDATE SKIP LOCKED.
 *
 * Згенеровано `npm run migration:generate` і поправлено руками: генератор
 * додав сюди `DROP INDEX idx_products_search_vector` і в down() відтворював
 * його звичайним b-tree. Це та сама фантомна різниця, що описана в README
 * («Чого ORM не вміє»): TypeORM не знає про `USING GIN`, тож щоразу хоче
 * «виправити» GIN-індекс. Обидва рядки видалено — b-tree не вміє оператор @@,
 * і повнотекстовий пошук з ДЗ-12 просто перестав би користуватись індексом.
 */

export class ConcurrencyQueue1790370772509 implements MigrationInterface {
    name = 'ConcurrencyQueue1790370772509'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tasks" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "type" text NOT NULL, "payload" jsonb NOT NULL, "status" text NOT NULL DEFAULT 'pending', "attempts" integer NOT NULL DEFAULT '0', "processed" integer NOT NULL DEFAULT '0', "locked_by" text, "result" text, "order_id" bigint, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "tasks_processed_natural" CHECK (processed >= 0), CONSTRAINT "tasks_attempts_natural" CHECK (attempts >= 0), CONSTRAINT "tasks_status_known" CHECK (status IN ('pending','done','failed')), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tasks_pending" ON "tasks" ("id") WHERE status = 'pending'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "balance_cents" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_balance_natural" CHECK (balance_cents >= 0)`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_ebc795fe637f4e8c0cfcb392e59" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_ebc795fe637f4e8c0cfcb392e59"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_balance_natural"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "balance_cents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tasks_pending"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
    }

}
