import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Початкова схема: та сама, що в db/schema.sql + db/indexes.sql з ДЗ-12.
 *
 * Згенерована `npm run migration:generate`, потім прочитана й поправлена
 * руками — саме так, як того вимагає постановка. Що дописано вручну й чому,
 * позначено коментарями нижче: @Index у TypeORM не вміє ані DESC, ані виразів,
 * ані `USING GIN`.
 *
 * down() реально відкочує: дропає дописані індекси, зовнішні ключі й таблиці
 * у зворотному порядку, а заразом прибирає запис про генеровану колонку з
 * typeorm_metadata.
 */

export class InitialSchema1790103845758 implements MigrationInterface {
    name = 'InitialSchema1790103845758'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["marketplace","public","products","GENERATED_COLUMN","search_vector","to_tsvector('simple', name || ' ' || description)"]);
        await queryRunner.query(`CREATE TABLE "products" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "seller_id" bigint NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "price_cents" integer NOT NULL, "currency" text NOT NULL DEFAULT 'UAH', "stock" integer NOT NULL DEFAULT '0', "is_published" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "search_vector" tsvector GENERATED ALWAYS AS (to_tsvector('simple', name || ' ' || description)) STORED, CONSTRAINT "products_stock_natural" CHECK (stock >= 0), CONSTRAINT "products_currency_iso" CHECK (currency ~ '^[A-Z]{3}$'), CONSTRAINT "products_price_positive" CHECK (price_cents > 0), CONSTRAINT "products_name_filled" CHECK (length(btrim(name)) > 0), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NOT NULL, "quantity" integer NOT NULL, "unit_price_cents" integer NOT NULL, CONSTRAINT "order_items_one_row_per_product" UNIQUE ("order_id", "product_id"), CONSTRAINT "order_items_price_positive" CHECK (unit_price_cents > 0), CONSTRAINT "order_items_quantity_positive" CHECK (quantity > 0), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "buyer_id" bigint NOT NULL, "status" text NOT NULL DEFAULT 'pending', "total_cents" integer NOT NULL DEFAULT '0', "currency" text NOT NULL DEFAULT 'UAH', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "paid_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "orders_paid_has_paid_at" CHECK (status IN ('pending','cancelled') OR paid_at IS NOT NULL), CONSTRAINT "orders_paid_at_sane" CHECK (paid_at IS NULL OR paid_at >= created_at), CONSTRAINT "orders_total_natural" CHECK (total_cents >= 0), CONSTRAINT "orders_currency_iso" CHECK (currency ~ '^[A-Z]{3}$'), CONSTRAINT "orders_status_known" CHECK (status IN ('pending','paid','shipped','delivered','cancelled')), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        // --- Правки руками поверх згенерованого (див. README, «Чого ORM не вміє») ---
        // @Index не вміє описати напрям сортування колонки, тож обидва індекси
        // orders створюються тут явно з `created_at DESC` — рівно як у
        // db/indexes.sql з ДЗ-12. Без DESC план на `ORDER BY created_at DESC
        // LIMIT n` став би `Index Scan Backward`, а не `Index Scan`.
        await queryRunner.query(`CREATE INDEX "idx_orders_pending_created_at" ON "orders" ("created_at" DESC) WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "idx_orders_buyer_created_at" ON "orders" ("buyer_id", "created_at" DESC)`);
        await queryRunner.query(`CREATE TABLE "users" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" text NOT NULL, "full_name" text NOT NULL, "city" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "users_email_unique" UNIQUE ("email"), CONSTRAINT "users_city_filled" CHECK (length(btrim(city)) > 0), CONSTRAINT "users_full_name_filled" CHECK (length(btrim(full_name)) > 0), CONSTRAINT "users_email_shape" CHECK (position('@' IN email) > 1), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        // Expression-індекс: у WHERE запиту стоїть lower(email), а не колонка,
        // тож індекс по email планер застосувати не може. @Index виразів не знає.
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_lower_email" ON "users" (lower(email))`);
        // GIN по tsvector: єдиний тип індексу, що вміє оператор @@.
        // USING GIN у TypeORM теж не виражається.
        await queryRunner.query(`CREATE INDEX "idx_products_search_vector" ON "products" USING GIN ("search_vector")`);
        // --- Кінець правок руками ---

        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_425ee27c69d6b8adc5d6475dcfe" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_5e90e93d0e036c3fadbaefa4d0a" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Дзеркально до правок руками в up()
        await queryRunner.query(`DROP INDEX "public"."idx_products_search_vector"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_lower_email"`);

        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_5e90e93d0e036c3fadbaefa4d0a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_425ee27c69d6b8adc5d6475dcfe"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_buyer_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_pending_created_at"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","search_vector","marketplace","public","products"]);
    }

}
