import 'reflect-metadata';
import { AppDataSource } from './data-source';
import { Order, OrderItem, Product, User } from './entities';

/**
 * Детермінований ідемпотентний seed.
 *
 *   npm run seed && npm run seed
 *
 * Другий запуск не дублює рядків і не падає. Механіка проста: усі id задані
 * явно, а `repository.save()` із наявним первинним ключем робить UPDATE, а не
 * INSERT. Саме заради цього ключі оголошені як GENERATED BY DEFAULT AS
 * IDENTITY, а не ALWAYS — у ALWAYS Postgres відмовився б приймати явний id.
 *
 * Дати теж фіксовані: інакше «детермінований» seed давав би різні дані на
 * кожному запуску, а CHECK orders_paid_at_sane вимагає paid_at >= created_at.
 */

const D = (iso: string) => new Date(iso);

/**
 * Баланс покупця — 1 000 000.00 грн у копійках. Свідомо надлишковий: у
 * demo:race має обмежувати САМЕ stock. Якби грошей не вистачало, число
 * успішних checkout-ів залежало б від того, хто першим дійшов до гаманця,
 * і стало б випадковим — а перевірка інваріанта вимагає рівно 10.
 */
export const SEED_BALANCE_CENTS = 100_000_000;

export const USERS: Array<Partial<User>> = [
  { id: '1', email: 'Olena.Shevchenko@example.com', fullName: 'Олена Шевченко', city: 'Київ', createdAt: D('2026-01-10T09:00:00Z'), balanceCents: SEED_BALANCE_CENTS },
  { id: '2', email: 'Andrii.Kovalenko@example.com', fullName: 'Андрій Коваленко', city: 'Львів', createdAt: D('2026-01-12T11:30:00Z'), balanceCents: SEED_BALANCE_CENTS },
  { id: '3', email: 'Iryna.Bondarenko@example.com', fullName: 'Ірина Бондаренко', city: 'Харків', createdAt: D('2026-01-15T14:05:00Z'), balanceCents: SEED_BALANCE_CENTS },
  { id: '4', email: 'Petro.Tkachuk@example.com', fullName: 'Петро Ткачук', city: 'Одеса', createdAt: D('2026-02-01T08:20:00Z'), balanceCents: SEED_BALANCE_CENTS },
  { id: '5', email: 'Sofiia.Melnyk@example.com', fullName: 'Софія Мельник', city: 'Дніпро', createdAt: D('2026-02-03T16:45:00Z'), balanceCents: SEED_BALANCE_CENTS },
  { id: '6', email: 'Taras.Kravchuk@example.com', fullName: 'Тарас Кравчук', city: 'Вінниця', createdAt: D('2026-02-07T10:10:00Z'), isActive: false, balanceCents: SEED_BALANCE_CENTS },
];

// Продавці — користувачі 1..3. Ціни в цілих копійках: 249900 = 2499.00 грн.
export const PRODUCTS: Array<Partial<Product>> = [
  { id: '1',  sellerId: '1', name: 'Шкіряні кросівки',        description: 'Оригінальні шкіряні кросівки від бренду Vesna. Колір: чорний.',        priceCents: 249900, stock: 14 },
  { id: '2',  sellerId: '1', name: 'Замшеві черевики',        description: 'Оригінальні замшеві черевики від бренду Vesna. Колір: коричневий.',     priceCents: 319900, stock: 7 },
  { id: '3',  sellerId: '1', name: 'Шкіряна сумка',           description: 'Оригінальна шкіряна сумка від бренду Vesna. Колір: бежевий.',           priceCents: 189900, stock: 21 },
  { id: '4',  sellerId: '2', name: 'Бавовняні футболки',      description: 'Оригінальні бавовняні футболки від бренду Karpaty. Колір: білий.',      priceCents:  59900, stock: 120 },
  { id: '5',  sellerId: '2', name: 'Вовняний джемпер',        description: 'Оригінальний вовняний джемпер від бренду Karpaty. Колір: сірий.',       priceCents: 149900, stock: 33 },
  { id: '6',  sellerId: '2', name: 'Зимова куртка',           description: 'Оригінальна зимова куртка від бренду Karpaty. Колір: синій.',           priceCents: 429900, stock: 9 },
  { id: '7',  sellerId: '3', name: 'Бездротові навушники',    description: 'Оригінальні бездротові навушники від бренду Dnipro. Колір: чорний.',    priceCents: 279900, stock: 45 },
  { id: '8',  sellerId: '3', name: 'Ігровий ноутбук',         description: 'Оригінальний ігровий ноутбук від бренду Dnipro. Колір: сірий.',         priceCents: 4899900, stock: 3 },
  { id: '9',  sellerId: '3', name: 'Компактний рюкзак',       description: 'Оригінальний компактний рюкзак від бренду Dnipro. Колір: зелений.',     priceCents:  99900, stock: 60 },
  { id: '10', sellerId: '3', name: 'Дорожня валіза',          description: 'Оригінальна дорожня валіза від бренду Dnipro. Колір: червоний.',        priceCents: 359900, stock: 12 },
];

export const ORDERS: Array<Partial<Order>> = [
  { id: '1', buyerId: '4', status: 'delivered', createdAt: D('2026-03-01T10:00:00Z'), paidAt: D('2026-03-01T10:12:00Z') },
  { id: '2', buyerId: '4', status: 'delivered', createdAt: D('2026-03-04T13:20:00Z'), paidAt: D('2026-03-04T13:25:00Z') },
  { id: '3', buyerId: '5', status: 'shipped',   createdAt: D('2026-03-08T09:15:00Z'), paidAt: D('2026-03-08T09:40:00Z') },
  { id: '4', buyerId: '5', status: 'paid',      createdAt: D('2026-03-11T18:05:00Z'), paidAt: D('2026-03-11T18:06:00Z') },
  { id: '5', buyerId: '6', status: 'cancelled', createdAt: D('2026-03-14T12:00:00Z'), paidAt: null },
  { id: '6', buyerId: '6', status: 'pending',   createdAt: D('2026-03-18T20:30:00Z'), paidAt: null },
  { id: '7', buyerId: '1', status: 'delivered', createdAt: D('2026-03-21T11:45:00Z'), paidAt: D('2026-03-21T12:00:00Z') },
  { id: '8', buyerId: '2', status: 'paid',      createdAt: D('2026-03-25T15:10:00Z'), paidAt: D('2026-03-25T15:11:00Z') },
];

// (order_id, product_id, quantity). Ціна підставиться з каталогу нижче —
// у реальному житті це знімок ціни на момент купівлі.
export const ITEMS: Array<[string, string, number]> = [
  ['1', '1', 1], ['1', '4', 2],
  ['2', '7', 1], ['2', '9', 1], ['2', '4', 3],
  ['3', '8', 1],
  ['4', '2', 1], ['4', '3', 1],
  ['5', '6', 1], ['5', '5', 2],
  ['6', '10', 1], ['6', '9', 2],
  ['7', '4', 5], ['7', '5', 1], ['7', '3', 1],
  ['8', '7', 2], ['8', '1', 1], ['8', '2', 1],
];

async function main(): Promise<void> {
  const ds = await AppDataSource.initialize();

  try {
    await ds.transaction(async (manager) => {
      // Порядок важливий: спершу батьки, потім діти — інакше FK відіб'є вставку.
      await manager.getRepository(User).save(USERS as User[]);
      await manager.getRepository(Product).save(PRODUCTS as Product[]);

      const priceOf = new Map(PRODUCTS.map((p) => [p.id!, p.priceCents!]));

      const items: Array<Partial<OrderItem>> = ITEMS.map(
        ([orderId, productId, quantity], index) => ({
          id: String(index + 1),
          orderId,
          productId,
          quantity,
          unitPriceCents: priceOf.get(productId)!,
        }),
      );

      // Сума замовлення мусить дорівнювати сумі позицій — рахуємо, а не
      // вигадуємо, інакше дані брешуть уже на старті.
      const totals = new Map<string, number>();
      for (const item of items) {
        const sum = item.quantity! * item.unitPriceCents!;
        totals.set(item.orderId!, (totals.get(item.orderId!) ?? 0) + sum);
      }

      const orders = ORDERS.map((order) => ({
        ...order,
        totalCents: totals.get(order.id!) ?? 0,
      }));

      await manager.getRepository(Order).save(orders as Order[]);
      await manager.getRepository(OrderItem).save(items as OrderItem[]);

      // Явні id не рухають послідовність IDENTITY: наступна автоматична
      // вставка спробувала б id = 1 і впала б на дублікаті ключа. Тому
      // після seed синхронізуємо лічильники з максимальним наявним id.
      for (const table of ['users', 'products', 'orders', 'order_items']) {
        await manager.query(
          `SELECT setval(pg_get_serial_sequence($1, 'id'), COALESCE((SELECT max(id) FROM "${table}"), 1))`,
          [table],
        );
      }
    });

    const counts = await ds.query<Array<Record<string, string>>>(`
      SELECT (SELECT count(*) FROM users)       AS users,
             (SELECT count(*) FROM products)    AS products,
             (SELECT count(*) FROM orders)      AS orders,
             (SELECT count(*) FROM order_items) AS order_items
    `);

    console.log('✔ seed виконано (ідемпотентно). Рядків у таблицях:');
    console.table(counts[0]);
  } finally {
    await ds.destroy();
  }
}

// Запускаємо main лише коли файл викликали напряму: демо ДЗ-14 імпортують
// звідси константи (SEED_BALANCE_CENTS, ORDERS) і не мусять перезаливати базу.
if (require.main === module) {
  main().catch((error: unknown) => {
    console.error('\n✖ seed не відпрацював.\n');
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
